# Generated by Django 2.1.2 on 2018-10-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181017_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='size',
            new_name='site_type',
        ),
    ]
