# Generated by Django 2.1.2 on 2018-10-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181017_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
