# Generated by Django 2.1.2 on 2018-10-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181016_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='name',
            new_name='sport_name',
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/sports'),
        ),
    ]
