# Generated by Django 2.1.2 on 2018-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
