# Generated by Django 2.1.2 on 2018-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20181016_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
