# Generated by Django 2.1.2 on 2018-10-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='is_active',
        ),
    ]
