# Generated by Django 2.1.2 on 2018-10-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_season_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='data.Competition'),
        ),
    ]
