# Generated by Django 2.1.2 on 2018-10-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_edition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='year',
        ),
        migrations.AddField(
            model_name='edition',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='data.Season'),
            preserve_default=False,
        ),
    ]
