# Generated by Django 2.1.2 on 2018-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20181019_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
