# Generated by Django 2.1.2 on 2018-10-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_edition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
