# Generated by Django 2.1.2 on 2018-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20181020_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='format',
            field=models.CharField(blank=True, choices=[('league', 'League Competition'), ('knockout', 'Knockout Competition')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(blank=True, choices=[('team', 'Team Competition'), ('individual', 'Individual Competition')], max_length=10, null=True),
        ),
    ]
