# Generated by Django 2.1.2 on 2018-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20181020_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='format',
            field=models.CharField(choices=[('league', 'League Competition'), ('knockout', 'Knockout Competition')], max_length=10),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('team', 'Team Competition'), ('individual', 'Individual Competition')], max_length=10),
        ),
    ]
