# Generated by Django 2.1.2 on 2018-10-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20181020_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='country',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='season',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
