# Generated by Django 2.1.2 on 2018-10-29 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20181029_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 17, 8, 56, 78430)),
        ),
    ]
