# Generated by Django 2.1.2 on 2018-10-29 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20181029_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 17, 39, 25, 7605)),
        ),
    ]
