# Generated by Django 2.1.2 on 2018-10-29 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20181029_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 21, 31, 13, 951429)),
        ),
    ]
