# Generated by Django 2.1.2 on 2018-11-01 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20181101_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 17, 32, 49, 79593)),
        ),
    ]
