# Generated by Django 2.1.2 on 2018-11-01 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20181101_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 20, 49, 41, 422661)),
        ),
    ]
