# Generated by Django 2.1.2 on 2018-11-05 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_auto_20181101_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 27, 50, 647494)),
        ),
    ]
