# Generated by Django 2.1.2 on 2018-11-05 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20181105_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 39, 27, 872315)),
        ),
    ]
