# Generated by Django 2.1.2 on 2018-11-05 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20181105_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 50, 5, 539577)),
        ),
    ]
