# Generated by Django 2.1.2 on 2018-11-06 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_auto_20181106_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 22, 9, 0, 379598)),
        ),
    ]
