# Generated by Django 2.1.2 on 2018-11-07 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20181106_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 11, 20, 37, 737541)),
        ),
    ]
