# Generated by Django 2.1.2 on 2018-11-07 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_auto_20181107_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 14, 29, 35, 595340)),
        ),
    ]
