# Generated by Django 2.1.2 on 2018-11-08 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_auto_20181108_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 20, 50, 53, 343095)),
        ),
    ]
