# Generated by Django 2.1.2 on 2018-10-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0021_auto_20181023_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('team', 'Team Competition'), ('individual', 'Individual Competition')], max_length=10)),
                ('format', models.CharField(choices=[('league', 'League Competition'), ('knockout', 'Knockout Competition')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='data.Country')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='data.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='football.Competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='data.Season', unique=True)),
            ],
        ),
    ]
