# Generated by Django 2.1.2 on 2018-10-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='country',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='sport',
        ),
        migrations.AlterField(
            model_name='edition',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='data.Competition'),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
