# Generated by Django 2.1.2 on 2018-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20181025_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos'),
        ),
        migrations.AddField(
            model_name='club',
            name='primary_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='primary_text',
            field=models.CharField(blank=True, default='#000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='secondary_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='secondary_text',
            field=models.CharField(blank=True, default='#000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/players'),
        ),
    ]
