# Generated by Django 2.1.2 on 2018-10-27 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20181026_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 16, 32, 4, 640674)),
        ),
        migrations.AddField(
            model_name='clubrecord',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 16, 32, 4, 640674)),
        ),
    ]
