# Generated by Django 2.1.2 on 2018-10-27 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20181027_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecord',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='player',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 16, 32, 56, 238774)),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_modified',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 16, 32, 56, 238774)),
        ),
    ]
