# Generated by Django 2.1.2 on 2018-10-27 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20181027_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 16, 38, 55, 861881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 16, 38, 55, 861881, tzinfo=utc)),
        ),
    ]
