# Generated by Django 2.1.2 on 2018-10-27 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_auto_20181027_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 19, 57, 12, 753695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 19, 57, 12, 753695, tzinfo=utc)),
        ),
    ]
