# Generated by Django 2.1.2 on 2018-10-28 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20181028_2028'),
        ('football', '0009_auto_20181027_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='current_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='data.Competition'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 20, 28, 53, 388494, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 20, 28, 53, 388494, tzinfo=utc)),
        ),
    ]
