# Generated by Django 2.1.2 on 2018-10-29 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20181028_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='football.Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
