# Generated by Django 2.1.2 on 2018-10-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20181029_1708'),
        ('football', '0011_auto_20181029_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecord',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='clubrecord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='clubrecord',
            name='short_name',
        ),
        migrations.AddField(
            model_name='clubrecord',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='data.Competition'),
        ),
        migrations.AlterField(
            model_name='clubrecord',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='data.Season'),
        ),
    ]
