# Generated by Django 2.1.2 on 2018-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20181029_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
