# Generated by Django 2.1.2 on 2018-10-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_auto_20181029_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='edition', to='football.Club'),
        ),
    ]
