# Generated by Django 2.1.2 on 2018-10-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_auto_20181030_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrecord',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='football.Edition'),
        ),
    ]
