# Generated by Django 2.1.2 on 2018-10-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_clubrecord_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrecord',
            name='edition',
        ),
    ]
