# Generated by Django 2.1.2 on 2018-10-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_clubrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrecord',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
