# Generated by Django 2.1.2 on 2018-10-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_clubrecord_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubrecord',
            old_name='goal_average',
            new_name='table_tiebreaker',
        ),
        migrations.RemoveField(
            model_name='clubrecord',
            name='goal_difference',
        ),
    ]
