# Generated by Django 2.1.2 on 2018-10-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20181030_1544'),
        ('football', '0022_auto_20181030_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubRecord',
            new_name='LeagueRecord',
        ),
    ]
