# Generated by Django 2.1.2 on 2018-11-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_auto_20181030_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=3, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_years', to='football.Club')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaguerecord',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='leaguerecord',
            name='club',
        ),
        migrations.RemoveField(
            model_name='leaguerecord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='leaguerecord',
            name='short_name',
        ),
        migrations.AddField(
            model_name='leaguerecord',
            name='clubseason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='football.ClubSeason'),
        ),
    ]
