# Generated by Django 2.1.2 on 2018-11-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_auto_20181101_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguerecord',
            name='competition',
        ),
        migrations.AddField(
            model_name='leaguerecord',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='football.Edition'),
        ),
    ]
