# Generated by Django 2.1.2 on 2018-11-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_auto_20181101_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerecord',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
