# Generated by Django 2.1.2 on 2018-11-06 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_auto_20181105_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
