# Generated by Django 2.1.2 on 2018-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_auto_20181106_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
