# Generated by Django 2.1.2 on 2018-11-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_edition_named_substitutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='football.Club')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='football.Game')),
                ('starter_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter1name', to='football.Player')),
                ('starter_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter10name', to='football.Player')),
                ('starter_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter11name', to='football.Player')),
                ('starter_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter2name', to='football.Player')),
                ('starter_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter3name', to='football.Player')),
                ('starter_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter4name', to='football.Player')),
                ('starter_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter5name', to='football.Player')),
                ('starter_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter6name', to='football.Player')),
                ('starter_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter7name', to='football.Player')),
                ('starter_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter8name', to='football.Player')),
                ('starter_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter9name', to='football.Player')),
                ('substitute_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub1name', to='football.Player')),
                ('substitute_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub10name', to='football.Player')),
                ('substitute_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub11name', to='football.Player')),
                ('substitute_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub12name', to='football.Player')),
                ('substitute_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub2name', to='football.Player')),
                ('substitute_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub3name', to='football.Player')),
                ('substitute_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub4name', to='football.Player')),
                ('substitute_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub5name', to='football.Player')),
                ('substitute_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub6name', to='football.Player')),
                ('substitute_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub7name', to='football.Player')),
                ('substitute_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub8name', to='football.Player')),
                ('substitute_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub9name', to='football.Player')),
            ],
        ),
    ]
